### PR TITLE
Add blog post UX writing lessons

### PR DESCRIPTION
**Pull request by sdvassil**
Just finished a class about UX writing and thought I would share some of what I learned on our blog. I did also update capitalization for headings in an old post. Couldn't let it go :grinning:

### CODE REVIEW

**Review by hougasian — APPROVED** [review]
Super post @sdvassil !!

**Review by tedk13 — COMMENTED** [review]
I was reading that!

**Comment by hougasian** [comment]
too slow!

**Comment by tedk13** [comment]
image

**Comment by hougasian** [comment]
not if i can't get this pr to build over in platform 😂

**Comment by hougasian** [comment]
creepy @jpvicari 😀

**Comment by hougasian** [comment]
Screen Shot 2022-01-19 at 2 34 57 PM

**Comment by sdvassil** [comment]
@jpvicari we miss you too 😀

**Comment by tedk13** [comment]
I miss your musk

**Comment by hougasian** [comment]
image

**Pull request merged**
