### PR TITLE
rimdev blog, v2

### PR DESCRIPTION
**Pull request by hougasian**
- Entire site redesign based on semantic ui
- bootstrap removed entirely
- new menu, post access, (cc) image tag, code blocks (new syntax highlighting)

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
Positives:

1. The posts read much nicer. The code blocks are clearer and the flow is pleasant.
2. The CC credit is really awesome.
3. The updates to the gem packages build the site much quicker as well.
4. I like the tooltip on the menu, maybe all the items should be done that way maybe?
5. The appearing / scroll menu at the top is very nice.

A few notes after running locally:

1. Menu is hard to read depending on the background image.

image

image


2. The name of @ScottSchwalm series is "Under The Decision Tree", we should stick to that rather than truncating the length it.

3. I would like a one click menu item that takes you **Home** or at least to the **Latest** post without having to open the sidebar.

4. Sidebar error

image

**Comment by khalidabuhakmeh** [comment]
The fix for the sidebar error is just to move the `articles-sidebar` include to the top of the file right after the body.

```liquid
<!DOCTYPE html>
<html>

{% include head.html %}

<body>
  {% include articles-sidebar.html %}
  {% include google-tag-manager.html %}

  <div class="pusher blurring">
    {{ content }}
    {% include footer.html %}
  </div>

  {% include script.html %}
  {% include freshness-hover.html %}

</body>
</html>
```

**Comment by khalidabuhakmeh** [comment]
Oh... mobile is busted.

image

It may make sense just to remove the hero image completely on mobile, and I'm not sure what to do about the menu.

**Comment by hougasian** [comment]
All addressed with the exception of a Home menu item. 
Like the idea of driving content forward, haven't developed a final menu concept. 
Should be

**Comment by hougasian** [comment]
onl

**Comment by hougasian** [comment]
@khalidabuhakmeh 
screen shot 2016-11-07 at 3 44 04 pm

**Comment by hougasian** [comment]
screen shot 2016-11-07 at 3 54 39 pm

**Comment by khalidabuhakmeh** [comment]
At a good point we can get more work done as we go along :)

**Pull request merged**
